[[VTK]]
arch = "aarch64"
git-tree-sha1 = "704570d6a02d3482c0037b142975cbabe9dd30f7"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[VTK.download]]
    sha256 = "fc3331a558116657a377b7328c5de113ab098ee3548d9bc021400dc41168de77"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "0fbddbc8357b1097d400c92b542e38d29349bf0b"
lazy = true
mpi = "mpich"
os = "macos"

    [[VTK.download]]
    sha256 = "e0a10b4b8bdd5a2c6f3c75b7db3b6a586c74f3a9a9f995bd1cffaca2cc9d23cd"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "397bf5452cb02b4f153bbf2e47ab7be478208da0"
lazy = true
mpi = "openmpi"
os = "macos"

    [[VTK.download]]
    sha256 = "106414895d9021fbccc47607da18c5f9146630cdd59d73c5c2afb1e36963ce07"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e908a17d6bac07a60b11e8f089241b18584f0c0"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "c963945c293ef3e5ccb63cf557a2205ab404f7cd012b99f3f3a4cd1e07d8ddce"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "970adf4ce006d9ece2c1ee0fc94c328453c688bb"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "7fcfb2f5e525c267fea698aee9c7aec5fa6ea61c75e472d7984246e970975302"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94d762aa0425eaf3726319719923c0955d76a84d"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "a9196b6da9cb945be4d26146e9e7fda114d58298da263e0a7eb79c133a6b34da"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fb62fb9227602b2d6ad0f04f87bc12d85a39dea"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "e93e4cdfdc970d3855c9fe35e085442fe4a321f72e03f684beda3196215df040"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cb88a6478256d1737214d05a8e153ce5f34ea5b"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "a86aa6b8a9aebb808e35f329fdb8952b0302dca79ba79cf3a35c995f8b2af806"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09a67ce357535f7dce939ffc8ff87b1697b8b3e1"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "03ec892d496e06d7ee8e992a5d1a63d0134ccee841cc491b87e317b2b4841b19"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "d1a3b768c8e5967641800e9af266b368ebe7d37a"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "8ddae5efb1db5fa5f0890c0c6e55c5b301112b2193bed994a36826d9235fbf3c"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "cdeaa04fa336454ee957c19a185379f4f58909f5"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[VTK.download]]
    sha256 = "54dd0d5e5535da74100390b5083405de4318a233c69293b0b77642a9de2d7b9c"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "2eb42da222a9c98558f4cf60e4684ff239018c4f"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "7c9e249eca0e5fea3f930b951c86a3ef0a61faadfabe279b20f184fe5a1cb5ce"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72f9bd170d749a4293d6a29a4866ed4e962d2b61"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "868b24587fd25f0a7794e7801ee46ab4e6bc050318325bc0137fd73f6f7411b3"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.powerpc64le-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bab8fad959a60705376320f22c56f8f85e04e0df"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "95595f6f440f8319d7d19898fd5863a122221124ea96640899eca242569fd923"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "930dfe9fc199ae6c121f180332f7462aaa6e8fe9"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "c2017c1fbdb056f636da6b9491ec0379f2d00f88a4638cc145225cc7ce13497c"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1f3de002d75fac338cd02b2081b2cb03e1e48f1"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "e0b4432c83cea7e9f07c01391d2a48e421a14aea6c492d03b62fc62069b37fa0"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.riscv64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78c44c957e1acce9fc794c2d3a5cf56ebffe3ff2"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "ec0fb6f6011202141aba64a6877cb6ee045d5db783b6954edd8cf86319493c7d"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.riscv64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a2c2885c781d98e39f1e33361bb7c1145d5dd53"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "502ff56e757df2b8e03e97b0026bb4ce6677d0cd29c194254a08907b7d0561b8"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.riscv64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "cdd34d5911e8c85c49e20e72bb63aaebe35506a7"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[VTK.download]]
    sha256 = "794914127d2508580415e90b11c656215f60e88ffc2d98e82464df6954985fc9"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "2a6757b53d81cc6db7f47b54f7d417a306510b6c"
lazy = true
mpi = "mpich"
os = "macos"

    [[VTK.download]]
    sha256 = "845235644d54aec5feefefc94cc69468db0ea99d607a329094ec5e052de13d43"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "521f3b439a7c138142096d5661d79ec82ac6e9bb"
lazy = true
mpi = "openmpi"
os = "macos"

    [[VTK.download]]
    sha256 = "6e87211abd6c9641197693ad6afcd0ef68af62eae25a7b623b5c4f19f6299c0b"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22ea0a7722228147b697437d2d5ee9c459a32aa3"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "4201c4176a1913ab91da97872f32bcbe305be8e74f20dc8f45fc0239d295b384"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94b50da158450962e395b73a164dbe78e78e28cc"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "fce1bb20ca4e81efeef0be6a00cb4a005238730c1d4a758ea47b073f4aabeced"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01fe50af560cb17c93ed04a49d48d7d1c7c5ac67"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "eec354c5128cd47cb5f4953be01bb4a9421a6362ed782aa61d0062510bc11677"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9de96d2aad42a9216b952a844f935c3ad2d55393"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "65863fd66086ce030bb38a79ae41236405c8fe383235fb1725c1e25a9320f88d"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fccc050c1896e4206518d9462cfd744b83535afa"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "9911525f17f312da8d1c8dafe1459cd0ad106cb4be5169297c2172de46b3d03d"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cdc74ed6ff7ed8017f92528d31bed8c1cef8d70"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "76fb57b67fada91343d5d2958de4494c583ae015ffa022b4d3288cde57a8fa19"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "4310ed2e30ea4e4f02182c5958b8d452f7316680"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "22ca75cd30a0a7e534811e3acca01adae6315d373c104614ea601f1ed56fa911"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "17c1ecb2f086ef3692a30586af5a4fdb68a75527"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[VTK.download]]
    sha256 = "9ce43a8003a791051101419d5ec9501ca87732ec788f4a24f59c63d3946d1cf4"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "f8024a537a4adc844966b507842dec1b95411ec1"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "2b5f1510edf522b7c45c2e3baef3ac934e87fe694e1b90dcbe54a34058a881f0"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.1+0/VTK.v9.6.1.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
