[[VTK]]
arch = "aarch64"
git-tree-sha1 = "a30d4f9a915347df8c41514f79193005f60487e0"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[VTK.download]]
    sha256 = "b56a0b55d7b35206d9fac06529efd400f798a28fc63945ae20b5a6070efb4282"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "5e52a320302c4a42ba6c9cc9255793288d511e41"
lazy = true
mpi = "mpich"
os = "macos"

    [[VTK.download]]
    sha256 = "9e568311969e960d359a26e85953f2f409b0c5e31e2fbb67f58978ae87fe8cef"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "c4c1ab2a2ce91ae9c91beaa595a19fe10a69c232"
lazy = true
mpi = "openmpi"
os = "macos"

    [[VTK.download]]
    sha256 = "08ca95232f999c790d4f584cc894a43d704c7456d6e817ec50de2a209be87d06"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "181c9b0f36ba204069a6d7a328ed505ba8e14c70"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "9486427bcdfedc0067df5f96ed04dae601fe84bc56530335ceebd6e848b63026"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7289446cf723eb8f48551e7238bf9f2ff2f02885"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "85320fb1829c352fb29288ddea8ee6fa012a91b157ce8b807497f45222aa34bb"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3db2f180c2cef323b9ff7f06e6b88c053c2ecb8f"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "0f472f5572b242b0eec99fb067cf510c31cff8da38afd8f80e2c70020d853ceb"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e2037cadaa2e8c3ce35c1846f4bdcb30fa44f3a"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "c0ae77696d6756e68b64929db70d2065ef54b907039289d06bea285e7f1e9074"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87f235a8ace430619c544d70527fd1041cdd7e5c"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "647bd8ae8980ed8e59ca9ee45e4b46e5e2194d8e2e1dcd4fa19476168ad3cc60"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f7b0e9a398e813d3431b3cf98291d68557c5ff7"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "9e0484bc33f7f757491c9ab7ebeb52486fd4d6ae18b4fdcac58adf5ad1ed656c"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "9eaa19adb96972eb26349ad8d4bbd5280853db05"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "43fa7780070cf9db852e6b8d90df18d7fa3850a6fc570001961a7e5ab05e9fad"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "edaee574aeb31cd4e213cd8c484605f6a1aa06e8"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[VTK.download]]
    sha256 = "4fb76808c51c7e213efaf2ffcfd17422cf5f769abd83f7285d9aed88cd50fb80"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "a4862ec2cd39f09f53689d699f38fe7bda37f173"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "6c38d1de76516dd95f87920ee104363b49676088db333089b191b86d1e6915e2"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfdcebd3ed40240e92e74823d4f8d4cd382bcb31"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "8ab988711bdca8b159f3ef0edd89d99008e692d309f62373f0b30ddff7b0a2b7"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.powerpc64le-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e81995f95d08770490451b84c5e29274a1e35947"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "2ac49b54a5f7d2ea7d2ca474ca507b1105e818ecc21659ab0dfa169caf9aeb49"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ef65a96b69c445cae6c24c730baaed3b74ea033"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "a2d0d2eccb3f636f9db011b1cc3f9bc4c604390cfdc2f51e828dfab6c88ec574"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ba4e42c37b97403661568a177713e8dd36ca2cd"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "4842d4a7bfee63cda0cc4388dccebef88e65d4bf4f063743bc524ef7e2ed71dd"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.riscv64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9f8b570617686d4ab96a4a7c152222b0f97512f"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "0d19137d6951195fb0689f45456356889ac90542c5ba462d0b672093c7ff4072"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.riscv64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b70d64c1f681787f37652848fb30baa0c33e635"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "5f1c5d3939c88e51b0131f8dcee2e310b0e63fdd1aeb6e55d774fa172d4005ab"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.riscv64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "7f14117dcfde85b579aac01bb4348e53df807292"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[VTK.download]]
    sha256 = "67af3c55f719291665e1f42e60610b6e098f4c6777d31980ffdc55ad72d48061"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "bb3da4da3e6c22333f69ce30961b440532940dd6"
lazy = true
mpi = "mpich"
os = "macos"

    [[VTK.download]]
    sha256 = "17e3339ba4bccb5354687a2fc2267ddce1b96af2f6673500f517a12b8948f148"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "7b24f9ad741a86728dc904c71ed72913f88e1657"
lazy = true
mpi = "openmpi"
os = "macos"

    [[VTK.download]]
    sha256 = "a683979b8626432e9fa079a02d7e3df30eff51aaef887a38e417d6961b14beba"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc578480adab6b6027c8ee98cd4c74109c28b6ea"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "f59e44a0b8014f6fcf120fb0059cc058ae917e4fa89d6cff862a7cf600f50df5"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbdae0ba48e7b6b29d51c17db836acbae047d1cd"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "c1a624e2a095590b8bfc21d43f42d3661673e074c39eb9f48fe3f1bdce80d659"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9c1e99f44c37bb476a25a511a97be78fe4f55a6"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "4e7643148db168ec3310c7cf3a2738781ae0378c603e915182bfe18dd85b507f"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dde89e417b3af6f18b42e3a2932bfae9c05e3f42"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "5c1d6eaae39f71cb4e1043e95a086b7841d45d74a8cf0bb6983c576b3af03bbe"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c41ceae2f80bd31278c39162ee7a332e1085a6c"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "7a15102b27d7012e0bc85be0b420885d52c1cbb763108c888c2776d176ae52f8"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b17583b4fd45292748e6f62539144748a7615ea"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "93486ec52d73e5cf969ed94f66fddad839be75e7e4f354c752a6c9334fe80b34"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "412bfabb6f951124f007fe2a67dd8af43b806822"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "182fe2b4a0bfb5f24788b5dd1d23ed0037f0b293388ac0931ce1c8a1df19a519"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "816792c118dee03d9de68d21cec2a5e278115c00"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[VTK.download]]
    sha256 = "410f05f273e4ae3ad35cfb648d7c49a2fd22fa490574173ab9b52203db080c7d"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "fa8a246f29ee17c26fb2cb4e785c61d699edb8bd"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "cf3ebb255f718b33923f9c3f4ec3d3bafb78ff2c1b8b81d7fbb530d9cb697429"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.7.0+0/VTK.v9.7.0.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
