[[VTK]]
arch = "aarch64"
git-tree-sha1 = "eef054f7dd081af5d7b97f0822a24dded3eb97e3"
lazy = true
mpi = "mpich"
os = "macos"

    [[VTK.download]]
    sha256 = "4e6c8ba8dab09df6ccd9cfd7f97fadab59f30826261884b60fbdd897d0e717e3"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "6dc8e770e7a9c82cbcda454b72e13221be7d2961"
lazy = true
mpi = "openmpi"
os = "macos"

    [[VTK.download]]
    sha256 = "cab1ec6512093c93086e950783eb396c2fc434f38a60b3aba25472dbc02ca336"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe3c81358726aeaed742b96ab49eefce547952f7"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "4d9328688e69c14cc217893fb87f66d280c0288063a659117ebc93caae1dddaa"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7b88dfac9871704d62c2c11e4a3077be32cd1b0"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "09e49a16fc131d3585422e1e44923d1da7625d4019d76b97e99895e7bc082502"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86a2f5f67aea069a4a6c8a8fa2bd310de03a7e37"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "4fe4b330f545a20085ab2e07fb98a33e5e7ac6b2b58e3f2438ff6fa522fe3191"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72ab489d73b7be1f7faabbc58c1f38d792ac31da"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "1adeb73865f44619ffde2ea009bdc83532530e58a641e3ecda4b700258fc27c0"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6a271fff8d46274ae8f40e6e89b5bec3400f76f"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "6e7114ef900ca37f6806619c870bd480311dbdd496f197c674ca301db3117bbb"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-linux-musl-cxx03-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c72c82b23f50b0a74ec7c56257f2cafbb10904f4"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "43b43e7f70726f8c7df78772f0686112426bc6f4aaebffcb29800c7f27565222"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-linux-musl-cxx03-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1cda4b6ad79568bc791ade9e4642bb5975cf9a9"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "36a950f7b0385a0ced364fd53677b4f623148564a2254e7a930c32bb78aad244"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9a487e6e81d6aab492bc36851ce4e80fc2a03b5"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "2dd6521be0ca3c2397f3d331572a04fdc798fc48cf8611c29f05568fb0504a93"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "31705724c567e7d7556e3abf8b5a91b75211f427"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[VTK.download]]
    sha256 = "e1de8868ca7b237b5a8c0220ab6f405526d445c00f52e5ba5ea67d3691212464"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "5df2f4e3bdf3dfac0b61ca7ebe17b0045812bf14"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "bc37a44b5548c49162ddd6ab714c5911e04ca1e5a61cb565459e9d1f0db73c25"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec360f1b0fe1e117fae3d17b0274153dcdb977ca"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "2109aeb74be3ee6ab9e1d2fd95de96f64a9ebdbc715ac55ff0cb1576cbdeadd7"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.powerpc64le-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1a4b27206b7a4c45a2dc6e8a1833d1f441f132b"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "8303ce35a111912b486855380f77cbd1d298d901e5d904e4a841038dd8e56029"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.powerpc64le-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18eadc0234ac765e344264e85ef3ab2530c4c8be"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "0d9fbb15987a5b1a0b397d4c47468cd038ceb4c465676713e2d406d23c110cd5"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "391ba78bcbeb9dc46fee431e799b1106f744f0d7"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "359e4ad33471bc6383761181a16738c783c974f417a4fdb9b3ef838cedbaa09a"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3351928c5f65392c804f663169adef37db53d04"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "f1d52da5fcddd9bda358939016275f60612f4e91bc6a6a19bd177e8a89f686c2"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.riscv64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a12c2b6e642b1770f07b3fe5f300a7fea35fab9"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "52538d584e3bdc4391edc1c7cfc056ec69d33dab7b4746ff6c2e1021cf5294df"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.riscv64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2008814f2c5c97da88a454cbcf1affc109f9208f"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "7a423fe269b137d6baf04f5d552aa81a263f0bda9f2e84739feb1c2090a38db6"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.riscv64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e898a336e69f27506a85ad8228e548dc7421b86"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "158f2725963368a4d3b10cc81469214e90abd6d04d040bd2ab324a2408089c58"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.riscv64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "82b12ea6ab01e79adc5de23a54092fbfd6314ca1"
lazy = true
mpi = "mpich"
os = "macos"

    [[VTK.download]]
    sha256 = "0fefda9187388fa2a0e18ae89cec4b16dc7ae3c119716ddf061f7a108a510326"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "46f48b1b0fff06eb5f5cbcfc005d307df257aada"
lazy = true
mpi = "openmpi"
os = "macos"

    [[VTK.download]]
    sha256 = "dfb01a6b5d659fbc2a5d55f4e659a8204d62d96b7730b2542913e0ca76006a73"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d5348714bc87601f766c17af4eb1947f58a9616"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "66ff3ab029b4c5aebc3ee6cbf4127a9a071cd44fbd35f8545f4e89bc6414acfe"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c743c32604dfa1c97433df56f7610b1099a5ca50"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "a7597cafde95aad5171e4e358a153270ad875b62a11d09884cfeefc785ff31f0"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8f3d44c8e1a628c1ea9f5b2bdde1212c264bc23"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "2c9dd4e69c0fd21c624142ec03ee957af13cabf1ba9f857d659063096ee3b6d5"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e506b5a95b88ee58be799826a1aadf6f16b7845f"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "3df9299db1ba7e7578970cbc325fea99728e46d7bfaab549c56591b66e5f79f8"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2b97642ddbd3c0494a645a58553b41078495fdd"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "90c5b9a916ffe985579dabfc31a83e16e06f3e073e54eb807bf48275fecbff67"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-linux-musl-cxx03-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85638af07767b28a345094c973bdd1e67217d1e5"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "864540b99689c4b35e7ddf9aca45acb1b809896944301b00c529ee3e61b66690"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-linux-musl-cxx03-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0802f143866e201cab5d65e15c327a39dcc6864d"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "5d9179d5d4b04a7e6fd2af74f93557997c1be1b945ea6288b28611880aedbe45"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b7d38621e1c0b09c234a906cef4b6901c2961b2"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "fd5c5b802f40666ed4a4afd5ca141ed6bca6499d4979ae7463fbf18d7d63f9da"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "56dcfe036132d66caac49ab2f11d23a4a14da2eb"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[VTK.download]]
    sha256 = "a39d0b04bec4ad56fa380b38f3e8224a56e47ead6d1dbb9f020e63d2312ab0f8"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "98aded4b493fe54e818fd767fcdfd6922d83963e"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "6027bd10ec6c3704ffa25e06e7133c1066709cd6a9e119387c6db1bfe6436494"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.5.2+0/VTK.v9.5.2.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
