[[VTK]]
arch = "aarch64"
git-tree-sha1 = "f8b3d35f7e117c844d5863195660013f2021a34a"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[VTK.download]]
    sha256 = "2f9ae35a3b83607879fbe31cb787314594afaa5a2fcfbd11b0f44e5c36149509"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "99a13fc591ab497d50d960a68f85f6ca3a94edf7"
lazy = true
mpi = "mpich"
os = "macos"

    [[VTK.download]]
    sha256 = "0d38335f7366d8aa85fb993cde40e3ae6dc27375bfe74719f003ec1641d68276"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "cb852a31d3a11261d2d79cdd058b6d946125394f"
lazy = true
mpi = "openmpi"
os = "macos"

    [[VTK.download]]
    sha256 = "c33d06d4c9069f2837cbecc937e542df76097636060e27b150a8a5547141c56b"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bedda9900e21391ddfc316b684feb4b3ff65b214"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "89e65431190e14df79d9ae21d85e9e22eaa012aaf2e2819d82fbe475c891577b"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e05df1188ef4559c3fd1e37938b1176b4cd65487"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "db00c59d25d58091f801ca4e17a115d2c3d2009ed54b7bcd639c6fda656d9936"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c33b379a6045c08f53623876c801d0a38f4846dc"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "c53a33c8a7cd66506402f36e5e83d90738c6c937a4b12bf4aa6e12d0a1f8e9f1"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c637e1925ec1c04f58d41fe3aa8c957647d0ea9"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "6c2abde7c4ad57a18857f58b1785ebf3316c3b25aa416fe1b1124113737a89cc"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90c54857de0effd716a2489192e0b93a7e7beed4"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "033dfb285e7a97b46d213d7d20f83bce059fd838fc394a72bc6fb7ca70ad5216"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50316e9eb67bf4a292c88c31fd0d3bbc33fdf5ea"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "9739882fe30d6529775830a469a44b1809f29496605559eecf2538d6406ddd13"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "927658ed8f6356f310a612935a03319b77e91d59"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "21ef702bb07b9ed96c5f4df60a7b51dbc7432d844dbf084371b01e5581d533b4"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "0c5b6729b372fc9c4761fbd54e0736a56dc6fe95"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[VTK.download]]
    sha256 = "ff53f0f988f60b0f2b1dc2df2b0cc5d8b85ff322ff472f45c455d012d2af9f57"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[VTK]]
arch = "aarch64"
git-tree-sha1 = "8c51073e280bb658e73f399181e55b477d284c00"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "ec26887aef95040f92c9adf9c644e1affafaf552c8062b63f5f88d144f3fda3b"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92224e6f164248fa7e5f1916c7a4b4a978d28457"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "be934afc0d9a7aaaf53f652e12e0c4c1a230707216cdc37440043211f4a58354"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.powerpc64le-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8763d0662cdf519b6950e58995286e0e375367f8"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "88cb934bd9608448018b2951296261a13c347f0952b1c27cdcf947ad346e2bfc"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84469dbe1af523739f62fb8b69a8205d15467f16"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "67c96020073b870236404bc7ead4ca74599b28df2f7a9710a7f24a81da63bcf1"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "284c576de85a3d3e0f3ba0470b32844311cffd9d"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "3e06e361f2508d4545a8ca27fd10ed600d4c45e5cfa2de915f978ba950518255"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.riscv64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c2011511543b8c39f5ffb245ba3642f9a4b0b65"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "3ec755bf812390b7a3aaff4a3a17b9724b961c581620e6ba29e9091b0c567388"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.riscv64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "581d44e3b6cc2fd3955d7c9e597950d78988c2a9"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "5cb286c645b01e728f57479f3ad74e4ea11ab2ec9385ad9f021615fb55f41ad0"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.riscv64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "7a778d822ffe0a406d7bd2e6f2efac49303fec55"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[VTK.download]]
    sha256 = "5c6e3f18ef6387ef18d168b50c61394600d62cb6ff3ee7c0ebe82197b8d04c9a"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "20893f6fb5c8591d4b78bb2d3a56cef49b248fd6"
lazy = true
mpi = "mpich"
os = "macos"

    [[VTK.download]]
    sha256 = "c8955e0fa91fe013db71a02a8dbad4dec7cf781bf71126ef4371fb4d1dbc95b5"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "c2245824e8b637092d043f77fae77002aa890380"
lazy = true
mpi = "openmpi"
os = "macos"

    [[VTK.download]]
    sha256 = "58f1ffb2aad310c0e8c4ee766997ff1afffb278f73cc9df98a07038c0042470d"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "579ec2347c8c4f735b397dd97083ac17b74dff21"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "2daffa0d5af2caaea835b3905fa85ca87d2f21799ec8fd1e63e990988bff176e"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5426cdcc0a9062f7a1e655a32bc8857a0b9864d5"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "c18cfa9c321f8d8a62c589bd51b78eafa2acf9816e3883d234e1aa1e512b350a"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90797104105511f50456c18cb4059a06b5f8092f"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "a3400b8097520fa543dcee497513fdb12f3e3015640995505f5732bba7742565"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "772c904cdfdf5d4dbe8f50e62774a0084c14a1c3"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[VTK.download]]
    sha256 = "48ed0816c7f373e5ed519862baaf54e6da7337b0607ba7fe015477ef755a1f39"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b8e8cbd846da9cc8286ce8b759e43308b9cf038"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[VTK.download]]
    sha256 = "b9b37c96caf408a5949a3ce96dd3509ac37fc0f54b67e5640da191a5a21b2ea3"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dd7a70e02e9338dd98676baad8f1d20af744a43"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[VTK.download]]
    sha256 = "ab3431cbc18ba30fd8eafc1dc46526560ff9dd95a9c598d79d70b92cce2944a9"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "2dee8be721a9bb4bf41fe85b1eb644d4d0d6511c"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "6dc0701d5f09a7a0674c8504e73a1472ef1f4b26f6844f03e2b894c04b1d124c"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "4ca9d366e855d70eaf295305eeb0fece001a7d1e"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[VTK.download]]
    sha256 = "4b9d3f80f2c94be51b2e73672c4572d72869f4c661e772c2019cfbb558ce807e"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[VTK]]
arch = "x86_64"
git-tree-sha1 = "ded3dc6381e671bb233cdd438b34c38c2d0a45e8"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[VTK.download]]
    sha256 = "9977caec0960991dc77eb909fcf0449c5430d7f57ba056225162bdc0734901a8"
    url = "https://github.com/JuliaBinaryWrappers/VTK_jll.jl/releases/download/VTK-v9.6.3+0/VTK.v9.6.3.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
